### ISSUE TITLE
Fix homepage

### ISSUE THREAD

**Issue by burturt** [pbrucla/cyber-instancer#15]
Homepage right now is just an svg - need to update to be more responsive and not have a scrollbar. Does not need to be anything fancy, just maybe update page to have no scrolling or something.

**Comment by bliutech** [comment]
@burturt Confused about this issue. What's the desired goal here? Is it to make the SVG completely fit on the full screen home page? I remember that there were some complaints about removing the scroll bar from the PBR website. Not sure if this is advised. 🤷

**Comment by burturt** [comment]
The homepage right now is quite literally just an image, which isn't very responsive or user friendly, causing an awkward scroll on the page. Only the top ~1/2 of the image is actually necessary and has text, so just making it no scroll (not just removing the scrollbar) would be a simple solution to fix right now, or a better solution would be to just redo the home page and have text be actual text and not text in an image.

Either way, long term homepage won't get much use as most people will be directed directly to a specific challenge page so fairly low priority/don't put in too much work unless you really want to.

**Comment by burturt** [comment]
I just did the hacky solution of removing scroll - considering it "fixed" for now
